-- 1. TABLA MAESTRA: RECETAS (Con TODO el detalle nutricional y rating)
CREATE TABLE recipes (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  name text NOT NULL,
  description text,
  image_url text,
  url text,
  total_time text,
  recipe_yield int DEFAULT 2,
  difficulty int,
  -- NUTRICIÓN DETALLADA
  calories_kcal float,      -- Valor energético (kcal)
  calories_kj float,        -- Valor energético (kJ)
  fat float,                -- Grasas
  fat_saturated float,      -- de las cuales saturadas
  carbs float,              -- Carbohidratos
  carbs_sugars float,       -- de los cuales azúcares
  fiber float,              -- Fibra
  protein float,            -- Proteínas
  sodium float,             -- Sodio
  potassium float,          -- Potassium
  calcium float,            -- Calcium
  iron float,               -- Iron
  serving_size float,       -- servingSize (ej: 467)
  -- VALORACIÓN
  rating_value float,       -- ratingValue (ej: 4.16)
  rating_count int,         -- ratingCount (ej: 51)
  local_image_name text     -- Para manejo de archivos locales
);

-- 2. TABLA CATÁLOGO: INGREDIENTES
CREATE TABLE ingredients (
  id text PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  name text NOT NULL,
  image_path text,
  slug text
);

-- 3. TABLA CATÁLOGO: ALÉRGENOS
CREATE TABLE allergens (
  id text PRIMARY KEY,
  name text NOT NULL,
  slug text,
  icon_path text
);

-- 4. TABLA CATÁLOGO: ETIQUETAS
CREATE TABLE tags (
  id text PRIMARY KEY,
  name text NOT NULL,
  type text,
  slug text
);

-- 5. TABLA CATÁLOGO: UTENSILIOS
CREATE TABLE utensils (
  id text PRIMARY KEY,
  name text NOT NULL
);

-- --- TABLAS DE CONEXIÓN ---

-- 6. RECETA + INGREDIENTE (Cantidades exactas)
CREATE TABLE recipe_ingredients (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipe_id uuid REFERENCES recipes(id) ON DELETE CASCADE,
  ingredient_id text REFERENCES ingredients(id) ON DELETE CASCADE,
  amount_text text,
  amount_value float,
  amount_unit text
);

-- 7. INGREDIENTES + ALÉRGENOS
CREATE TABLE ingredient_allergens (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ingredient_id text REFERENCES ingredients(id) ON DELETE CASCADE,
  allergen_id text REFERENCES allergens(id) ON DELETE CASCADE
);

-- 8. RECETA + ETIQUETAS
CREATE TABLE recipe_tags (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipe_id uuid REFERENCES recipes(id) ON DELETE CASCADE,
  tag_id text REFERENCES tags(id) ON DELETE CASCADE
);

-- 9. RECETA + UTENSILIOS
CREATE TABLE recipe_utensils (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipe_id uuid REFERENCES recipes(id) ON DELETE CASCADE,
  utensil_id text REFERENCES utensils(id) ON DELETE CASCADE
);

-- 10. INSTRUCCIONES (Paso a paso con Caption)
CREATE TABLE instructions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipe_id uuid REFERENCES recipes(id) ON DELETE CASCADE,
  step_number int,
  caption text,
  content text,
  step_image text
);